#### 效率比对

In [1]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
% time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 14.1 ms


In [3]:
% time for _ in range(10): my_list2 =[x * 2 for x in my_list]

Wall time: 705 ms


## ndarray: 多维数组对象

In [4]:
# 生成随机数组（标准正态分布）
data = np.random.randn(2, 3)
print(f"data type: {type(data)}")
print(data)

data type: <class 'numpy.ndarray'>
[[ 0.40940042  0.23747917 -0.4616224 ]
 [ 1.46634919  0.00636971 -1.57076056]]


In [5]:
print(data * 10)
print(data + data)

[[  4.09400415   2.3747917   -4.61622404]
 [ 14.66349194   0.06369714 -15.70760559]]
[[ 0.81880083  0.47495834 -0.92324481]
 [ 2.93269839  0.01273943 -3.14152112]]


一个ndarray是一个通用的多维**同类**数据容器
每个数组都有一个shape属性，用来表征数组每一维度的数量
每个数组都有一个dtype属性，用来描述数组的数据类型
每个数组都有一个ndim属性，用来描述数组的维度

In [6]:
print(f"data shape: {data.shape}")
print(f"data dtype: {data.dtype}")
print(f"data ndim: {data.ndim}")

data shape: (2, 3)
data dtype: float64
data ndim: 2


In [17]:
# 指定数据类型
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print(arr)
print(f"arr dtype: {arr.dtype}")

[1 2 3 4 5]
arr dtype: int32


In [18]:
# 用astype显式转换数组数据类型
float_arr = arr.astype(np.float64)
print(float_arr)
print(f"float arr dtype: {float_arr.dtype}")

[1. 2. 3. 4. 5.]
float arr dtype: float64


<font color="red">把浮点型转换为整型时，小数点后的部分被消除</font>

In [20]:
# 浮点数转换为字符串
# numpy可能会修正大小或删除输入且不发出警告
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings)
nums = numeric_strings.astype(np.float64)
print(nums)

[b'1.25' b'-9.6' b'42']
[ 1.25 -9.6  42.  ]


<font color="green">当转换类型失败时会抛出一个TypeError</font>

### 生成ndarray
#### 列表与数组的转换

In [8]:
# 列表转换为一维数组
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(f"arr1 type: {type(arr1)}")
print(arr1)

arr1 type: <class 'numpy.ndarray'>
[6.  7.5 8.  0.  1. ]


In [9]:
# 嵌套序列自动转换为多维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(f"arr2 type: {type(arr2)}")
print(arr2)

arr2 type: <class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]


#### 创建新数组

In [10]:
# np.zeros创造全零数组，可指定数据类型，默认为float64
arr = np.zeros(10, "int")
print(arr)
arr = np.zeros((3, 6))
print(arr)

[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
# np.empty创建没有初始化的数组
arr = np.empty((2, 3, 2))
print(arr)

[[[7.11662123e-312 3.16202013e-322]
  [0.00000000e+000 0.00000000e+000]
  [1.35807731e-312 3.50759109e-033]]

 [[3.89277410e-033 4.08784767e+179]
  [1.57429463e+161 3.21991057e-057]
  [7.61381399e-042 8.84701005e+165]]]


In [12]:
# 创建高维数组时需要shape传递一个元组
print(arr.ndim)

3


#### 创建顺序数组

In [13]:
# arange是range的数组版
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### 其他创建新数组的函数
+ asarray: 将输入转换为ndarray，如果输入是ndarray则不再复制
+ ones: 根据给定形状和数据类型生成全1数组
+ ones_like: 根据所给的数组生成一个形状一样的全1数组
+ zeros: 根据所给的数组生成一个形状一样的全0数组
+ empty: 根据给定形状生成一个没有初始化数值的空数组
+ empty_like: 根据所给数组生成一个形状一样但没有初始化数值的空数组
+ full: 根据给定形状生成一个指定数值的数组
+ full_like: 根据所给数组生成一个形状一样但内容是指定的数组
+ eye, identity: 生成一个N×N特征矩阵（对角线位置都是1，其余位置是0）