### numpy.random模块
#### 正态分布样本数组

In [1]:
import numpy as np

In [3]:
samples = np.random.normal(size=(4,4))
print(samples)

[[-0.33905604  0.64489876 -0.55003872 -0.53057469]
 [ 0.73798453 -2.07696337 -2.25518957 -0.58975119]
 [-0.07684349 -1.03505393  1.2375501  -0.12417202]
 [-0.68404629  0.86681332  0.69489428  0.62792419]]


#### 伪随机数
> 由具有确定性行为的算法根据随机数生成器中的随机数种子生成的
> 可通过np.random.seed更改NumPy的随机数种子

In [4]:
np.random.seed(1234)

为使数据独立于其他的随机数状态，可以使用np.random.RandomState创建一个随机数生成器

In [6]:
rng = np.random.RandomState(1234)
print(rng.randn(10))

[ 0.47143516 -1.19097569  1.43270697 -0.3126519  -0.72058873  0.88716294
  0.85958841 -0.6365235   0.01569637 -2.24268495]


其他random模块函数见P119