## 一维数组

In [1]:
import numpy as np

In [2]:
arr = np.array(np.arange(10))

In [3]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# 一维数组索引
print(arr[2])

2


In [5]:
# 切片
slice = arr[3:8]
print(slice)

[3 4 5 6 7]


In [6]:
# 修改slice的同时会修改arr
print("former array:")
print(arr)

slice[1] = 10

print("present array:")
print(arr)

former array:
[0 1 2 3 4 5 6 7 8 9]
present array:
[ 0  1  2  3 10  5  6  7  8  9]


In [7]:
# 不写切片值得到的就是arr的全部引用
print("former array:")
print(arr)

slice = arr[:]
slice[4] = 4

print("present array:")
print(arr)

former array:
[ 0  1  2  3 10  5  6  7  8  9]
present array:
[0 1 2 3 4 5 6 7 8 9]


In [8]:
# 通过copy方法得到一个新的副本
slice = arr.copy()
slice[2] = 8
print(slice)
print(arr)

[0 1 8 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


## 二维数组

In [30]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# 只用一个索引值i得到的是第i行对应的一维数组
print(arr2d[1])

[4 5 6]


In [12]:
# 用两个索引值i和j得到对应元素
# 法1
print(arr2d[1][1])
# 法2
print(arr2d[1,1])

5
5


### 切片

In [18]:
print(arr2d[:2])

[[1 2 3]
 [4 5 6]]


In [20]:
# 多组切片
print(arr2d[:2,1:])

[[2 3]
 [5 6]]


In [23]:
# 索引与切片混合使用，可以得到低维度的切片
print(arr2d[1,:2])
print(arr2d[:2,2])

[4 5]
[3 6]


In [27]:
# 更高维度上进行切片
print(arr2d[:,:1])

[[1]
 [4]
 [7]]


In [28]:
# 注意区分
print(arr2d[:,0])

[1 4 7]


In [29]:
# 对切片赋值
arr2d[:,:1] = 0
print(arr2d)

[[0 2 3]
 [0 5 6]
 [0 8 9]]


In [31]:
# 没带冒号同理
arr2d[:,1] = 0
print(arr2d)

[[1 0 3]
 [4 0 6]
 [7 0 9]]


## 多维数组

In [13]:
# 2 x 2 x 3的多维数组
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [14]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
# 可以省略后续索引值，返回的对象是降低一个维度的数组
print(arr3d[0])

[[1 2 3]
 [4 5 6]]


In [16]:
print(arr3d[0,0])

[1 2 3]


In [17]:
print(arr3d[0,0,0])

1


### 布尔索引

`randn(d0,d1,d2,...,dn)`方法
+ 返回维度为(d0,d1,d2,...,dn)的数组
+ 该数组中的数据呈标准正态分布

官方说明：
random.randn(d0, d1, ..., dn)
Return a sample (or samples) from the “standard normal” distribution.

> Note
>
> This is a convenience function for users porting code from Matlab, and wraps standard_normal. That function takes a tuple to specify the size of the output, which is consistent with other NumPy functions like numpy.zeros and numpy.ones.

> Note
>
> New code should use the standard_normal method of a default_rng() instance instead; please see the Quick Start.

If positive int_like arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1. A single float randomly sampled from the distribution is returned if no argument is provided.

Parameters
d0, d1, …, dnint, optional
The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.

Returns
Zndarray or float
A (d0, d1, ..., dn)-shaped array of floating-point samples from the standard normal distribution, or a single such float if no parameters were supplied.

In [32]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)

In [33]:
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.10470272  0.44397332 -0.35596666  0.94090952]
 [-0.38904699  0.53721142  0.98817687 -1.07540849]
 [ 0.59859986 -0.00810663  0.38632607  1.41700916]
 [ 0.60499769  0.80505161 -1.49550668 -1.03135535]
 [-0.20495304 -0.4338573   1.80897569  0.14247721]
 [-0.65114644 -1.81334329  0.27902658 -0.26561524]
 [-0.57489183  0.93156104 -1.95182938  0.72465023]]


假设每个人名都和data数组的一行相对应，并且我们想要选中所有'Bob'对应的行
↓
用names数组和字符串'Bob'比较，产生一个布尔值数组

<font color="red">使用布尔值索引选择数据时，**总是**生成数据的**拷贝**</font>

In [34]:
res = names == 'Bob'
print(res)

[ True False False  True False False False]


In [35]:
# 通过该布尔数组从data中获取和'Bob'相关的数据
data_of_Bob = data[res]
print(data_of_Bob)

[[-0.10470272  0.44397332 -0.35596666  0.94090952]
 [ 0.60499769  0.80505161 -1.49550668 -1.03135535]]


In [36]:
# 通过~符号可以对一个通用条件取反
data_not_of_Bob = data[~res]
print(data_not_of_Bob)

[[-0.38904699  0.53721142  0.98817687 -1.07540849]
 [ 0.59859986 -0.00810663  0.38632607  1.41700916]
 [-0.20495304 -0.4338573   1.80897569  0.14247721]
 [-0.65114644 -1.81334329  0.27902658 -0.26561524]
 [-0.57489183  0.93156104 -1.95182938  0.72465023]]


In [37]:
# 组合条件时用 & 和 |
res = (names == 'Bob') | (names == 'Joe')
print(res)

[ True  True False  True False  True  True]


<font color="red">and 和 or 对布尔值数组没用！！</font>

In [38]:
# 显示筛选出来的组合条件对应的数据
data_of_two = data[res]
print(data_of_two)

[[-0.10470272  0.44397332 -0.35596666  0.94090952]
 [-0.38904699  0.53721142  0.98817687 -1.07540849]
 [ 0.60499769  0.80505161 -1.49550668 -1.03135535]
 [-0.65114644 -1.81334329  0.27902658 -0.26561524]
 [-0.57489183  0.93156104 -1.95182938  0.72465023]]


In [39]:
# 将data中小于0的数值全部设为0
data[data < 0] = 0
print(data)

[[0.         0.44397332 0.         0.94090952]
 [0.         0.53721142 0.98817687 0.        ]
 [0.59859986 0.         0.38632607 1.41700916]
 [0.60499769 0.80505161 0.         0.        ]
 [0.         0.         1.80897569 0.14247721]
 [0.         0.         0.27902658 0.        ]
 [0.         0.93156104 0.         0.72465023]]


In [40]:
# 利用一维布尔值数组对每一行或每一列设置数值
data[names != 'Joe'] = 7
print(data)

[[7.         7.         7.         7.        ]
 [0.         0.53721142 0.98817687 0.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.         0.         0.27902658 0.        ]
 [0.         0.93156104 0.         0.72465023]]


### 神奇索引
> 使用整数数组进行数据索引

+ 也会将数据复制到一个新的数组中

In [49]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [51]:
print(arr[[4,3,0,6]])

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


In [44]:
# 使用负索引
print(arr[[-3,-5,-7]])

[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


In [54]:
# 传递多个索引数组
arr = np.arange(32).reshape((8,4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [55]:
# 以列为索引顺序
print(arr[:,[3,2,1,0]])

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]
 [19 18 17 16]
 [23 22 21 20]
 [27 26 25 24]
 [31 30 29 28]]


In [46]:
print(arr[[1,5,7,2],[0,3,1,2]])

[ 4 23 29 10]


发现元素(1, 0), (5, 3), (7, 1), (2, 2) 被选中

要想选择矩阵中行列的子集所形成的矩形区域，下面是一种实现方法

In [48]:
res = arr[[1,5,7,2]][:,[0,3,1,2]]
print(res)

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
