In [1]:
import numpy as np

sort 方法

In [2]:
arr = np.random.randn(6)
print(arr)

[ 0.12851733 -1.75120592 -2.20902163 -0.086358    0.97127951  0.0960556 ]


np.sort方法返回的是已经排序好的数组拷贝

In [7]:
print(type(arr.sort()))
print(type(np.sort(arr)))
print(arr)

<class 'NoneType'>
<class 'numpy.ndarray'>
[-2.20902163 -1.75120592 -0.086358    0.0960556   0.12851733  0.97127951]


在多维数组中根据传递的axis值，沿着轴向对每个一维数据段进行排序

In [10]:
arr = np.random.randn(5,3)
print(arr)

[[ 2.21201276 -1.24353831  0.92569029]
 [-0.4700942  -0.47650212  0.68487028]
 [-2.07914325  1.64648223 -1.69322791]
 [-0.67121995  2.30875836 -1.20013654]
 [ 0.92395928  1.26517168 -0.12540385]]


In [11]:
arr.sort(1)
print(arr)

[[-1.24353831  0.92569029  2.21201276]
 [-0.47650212 -0.4700942   0.68487028]
 [-2.07914325 -1.69322791  1.64648223]
 [-1.20013654 -0.67121995  2.30875836]
 [-0.12540385  0.92395928  1.26517168]]


In [12]:
arr.sort(0)
print(arr)

[[-2.07914325 -1.69322791  0.68487028]
 [-1.24353831 -0.67121995  1.26517168]
 [-1.20013654 -0.4700942   1.64648223]
 [-0.47650212  0.92395928  2.21201276]
 [-0.12540385  0.92569029  2.30875836]]
