In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5,4)
print(arr)

[[-0.4179589   2.09593934 -0.21102751 -0.53757302]
 [ 0.14366172  0.59176277 -0.79600946 -0.33012904]
 [-1.73480637  0.57561853  0.85467053 -1.79127921]
 [-0.63982156  0.27368207 -1.86608983 -0.73446697]
 [ 0.31442975 -0.41154637  1.87095528 -2.23689437]]


In [4]:
# 求所有元素的数学平均值
print(arr.mean())
print(np.mean(arr))

-0.24934413059736488
-0.24934413059736488


In [5]:
# 求所有元素的总和
print(arr.sum())
print(np.sum(arr))

-4.986882611947298
-4.986882611947298


In [9]:
# 通过指定参数axis，用于计算给定轴向上的统计值，形成一个下降一维度的数组
print(arr.mean(axis=1))
print(arr.sum(axis=1))

[ 0.23234498 -0.0976785  -0.52394913 -0.74167407 -0.11576393]
[ 0.92937991 -0.39071401 -2.09579652 -2.96669629 -0.4630557 ]


### 累计函数
#### cumsum
+ 从0开始元素累计和

In [10]:
arr = np.arange(9).reshape((3,3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
print(arr.cumsum())

[ 0  1  3  6 10 15 21 28 36]


In [12]:
print(arr.cumsum(axis=0))

[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]


#### cumprod
+ 从1开始元素累计积

In [14]:
print(arr.cumprod())

[0 0 0 0 0 0 0 0 0]


In [17]:
print(arr.cumprod(axis=0))

[[ 0  1  2]
 [ 0  4 10]
 [ 0 28 80]]


In [18]:
print(arr.cumprod(axis=1))

[[  0   0   0]
 [  3  12  60]
 [  6  42 336]]
