In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6]])

In [3]:
print(arr*arr)

[[ 1  4  9]
 [16 25 36]]


In [4]:
print(arr-arr)

[[0 0 0]
 [0 0 0]]


带标量的计算会把计算参数传递给数组的每一个元素

In [5]:
print(1/arr)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [6]:
print(arr**0.5)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


同尺寸数组之间比较会产生一个**布尔型**数组

In [7]:
arr2 = np.array([[0,4,1],[7,2,12]])

In [8]:
print(arr>arr2)

[[ True False  True]
 [False  True False]]


其他见《利用Python进行数据分析P113》