In [2]:
import numpy as np

单一文件会默认保存为.npy文件

In [3]:
# 数组保存
arr = np.arange(10)
np.save('some_array',arr)

In [4]:
# 数组载入
arr_new = np.load("some_array.npy")
print(arr_new)

[0 1 2 3 4 5 6 7 8 9]


保存多个数组使用np.savez方法，保存后的.npz元素在加载时返回一个字典对象

In [5]:
arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])
arr3 = np.array([1,2,3,4,5])
np.savez('array_archive.npz',a=arr1,b=arr2,c=arr3)

In [6]:
arch = np.load('array_archive.npz')
print(arch['a'])
print(arch['b'])
print(arch['c'])

[1 3 5 7 9]
[ 2  4  6  8 10]
[1 2 3 4 5]
