numpy中的*表示的是矩阵的逐元素乘积，要进行矩阵点乘需用到dot方法

In [2]:
import numpy as np

In [3]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[ 6 23]
 [-1  7]
 [ 8  9]]


In [4]:
# 法1
res = x.dot(y)
print(res)

[[ 28  64]
 [ 67 181]]


In [5]:
# 法2
res = np.dot(x,y)
print(res)

[[ 28  64]
 [ 67 181]]


In [6]:
# 法3
res = x @ y
print(res)

[[ 28  64]
 [ 67 181]]


### numpy.linalg

In [7]:
from numpy.linalg import inv, qr

In [8]:
X = np.random.randn(5,5)
print(X)

[[-0.60295435  0.52737423  0.29564464 -1.26746161  0.64594783]
 [ 0.39378153  0.84987037  0.09829363  1.10874571 -0.81147179]
 [ 0.04875389  1.45708526 -0.25228942 -0.44458711 -0.53608224]
 [ 0.93117087 -0.21124316  0.43908342  0.39844376  1.56594009]
 [ 0.35601025 -0.14614434 -0.6481696   0.67087514 -0.29166879]]


In [9]:
# 矩阵求逆
mat = X.T.dot(X)
print(mat)

[[ 1.51481726 -0.16101312  0.02625258  1.78900737  0.61916497]
 [-0.16101312  3.18948253 -0.12618203 -0.55615091 -1.41827551]
 [ 0.02625258 -0.12618203  0.77363542 -0.41346179  1.12308556]
 [ 1.78900737 -0.55615091 -0.41346179  3.64226458 -1.05182897]
 [ 0.61916497 -1.41827551  1.12308556 -1.05182897  3.90035827]]


In [23]:
# XT * X * XT * X
res = mat.dot(inv(mat))
print(res)

[[ 1.00000000e+00  3.48297921e-16 -1.63229395e-16  2.71665979e-15
   8.92136682e-16]
 [ 1.05506211e-15  1.00000000e+00 -5.58344752e-16 -1.45582980e-15
  -1.89906542e-15]
 [-1.39057837e-15 -1.15879973e-16  1.00000000e+00 -1.68179781e-15
  -1.80670319e-15]
 [ 2.60504819e-15  6.20671770e-16 -1.05736103e-15  1.00000000e+00
   8.83530434e-16]
 [-1.98407590e-15 -8.62342602e-16  1.58167291e-15 -1.24504730e-15
   1.00000000e+00]]


In [31]:
# 保留几位小数
print(np.around(res,decimals=1))

[[ 1.  0. -0.  0.  0.]
 [ 0.  1. -0. -0. -0.]
 [-0. -0.  1. -0. -0.]
 [ 0.  0. -0.  1.  0.]
 [-0. -0.  0. -0.  1.]]
