## 一维数组

In [1]:
import numpy as np

In [2]:
arr = np.array(np.arange(10))

In [3]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# 一维数组索引
print(arr[2])

2


In [5]:
# 切片
slice = arr[3:8]
print(slice)

[3 4 5 6 7]


In [6]:
# 修改slice的同时会修改arr
print("former array:")
print(arr)

slice[1] = 10

print("present array:")
print(arr)

former array:
[0 1 2 3 4 5 6 7 8 9]
present array:
[ 0  1  2  3 10  5  6  7  8  9]


In [7]:
# 不写切片值得到的就是arr的全部引用
print("former array:")
print(arr)

slice = arr[:]
slice[4] = 4

print("present array:")
print(arr)

former array:
[ 0  1  2  3 10  5  6  7  8  9]
present array:
[0 1 2 3 4 5 6 7 8 9]


In [8]:
# 通过copy方法得到一个新的副本
slice = arr.copy()
slice[2] = 8
print(slice)
print(arr)

[0 1 8 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


## 二维数组

In [30]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# 只用一个索引值i得到的是第i行对应的一维数组
print(arr2d[1])

[4 5 6]


In [12]:
# 用两个索引值i和j得到对应元素
# 法1
print(arr2d[1][1])
# 法2
print(arr2d[1,1])

5
5


### 切片

In [18]:
print(arr2d[:2])

[[1 2 3]
 [4 5 6]]


In [20]:
# 多组切片
print(arr2d[:2,1:])

[[2 3]
 [5 6]]


In [23]:
# 索引与切片混合使用，可以得到低维度的切片
print(arr2d[1,:2])
print(arr2d[:2,2])

[4 5]
[3 6]


In [27]:
# 更高维度上进行切片
print(arr2d[:,:1])

[[1]
 [4]
 [7]]


In [28]:
# 注意区分
print(arr2d[:,0])

[1 4 7]


In [29]:
# 对切片赋值
arr2d[:,:1] = 0
print(arr2d)

[[0 2 3]
 [0 5 6]
 [0 8 9]]


In [31]:
# 没带冒号同理
arr2d[:,1] = 0
print(arr2d)

[[1 0 3]
 [4 0 6]
 [7 0 9]]


## 多维数组

In [13]:
# 2 x 2 x 3的多维数组
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [14]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
# 可以省略后续索引值，返回的对象是降低一个维度的数组
print(arr3d[0])

[[1 2 3]
 [4 5 6]]


In [16]:
print(arr3d[0,0])

[1 2 3]


In [17]:
print(arr3d[0,0,0])

1
