numpy.where方法
+ 三元表达式x if condition else y的向量化版本

In [2]:
import numpy as np

In [3]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

假设cond中的元素为True时，选择xarr中的元素，为False时选择yarr中的元素

In [4]:
result = [(x if c else y)
          for x,y,c in zip(xarr, yarr, cond)]
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


上述方法会很慢，而且当数组是多维时无法奏效

In [26]:
# 使用np.where方法
arr = np.random.randn(4,4)
print(arr)
print(arr>0)

[[-0.25647521 -0.02796995  0.92196054  0.61724743]
 [ 1.19661376 -0.92676618 -1.34083646 -0.3721946 ]
 [ 0.20725042  0.76725117  0.88665815 -1.26774409]
 [ 1.37922824  0.53315327 -0.62527415  0.32462448]]
[[False False  True  True]
 [ True False False False]
 [ True  True  True False]
 [ True  True False  True]]


In [27]:
# 大于0的元素设置为2，否则设置为-2
print(np.where(arr>0, 2, -2))

[[-2 -2  2  2]
 [ 2 -2 -2 -2]
 [ 2  2  2 -2]
 [ 2  2 -2  2]]


传递给where的数组可以是同等大小的数组，也可以是标量

In [28]:
# 仅将正值设为2
print(np.where(arr>0,2,arr))

[[-0.25647521 -0.02796995  2.          2.        ]
 [ 2.         -0.92676618 -1.34083646 -0.3721946 ]
 [ 2.          2.          2.         -1.26774409]
 [ 2.          2.         -0.62527415  2.        ]]
