<font color="red">注意：转置和换轴得到的都是数组的视图而没有复制数组</font>
### 一维数组转置
不区分行变量和列变量，转置后不变

In [1]:
import numpy as np

In [2]:
arr1d = np.array([1,2,3,4])
print(arr1d.T)

[1 2 3 4]


### 二维数组转置
同线性代数中二维数组的转置

In [3]:
arr2d = np.arange(32).reshape((8,4))
print(arr2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [4]:
print(arr2d.T)

[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]


### 高维数组转置
<font color="red" size=6>设axis=i，则Numpy沿着第i个下标变化的方向进行操作</font>
[对轴的理解](https://zhuanlan.zhihu.com/p/31275071)
#### 交换两个轴
`swapaxes`方法
+ 接受一对轴编号作为参数，并对轴进行调整用于重组数据

In [5]:
arr = np.arange(16).reshape((2,2,4))
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [6]:
print(arr.swapaxes(0,1))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


#### 自定义轴顺序
`transpose`方法
对于数组arr，默认的轴编号为(0,1,2)，语句arr.transpose((1,0,2))即将第一个轴和第二个轴交换，此时，之前arr中元素8的索引为(1,0,0)，转换之后元素8的索引为(0,1,0)

In [7]:
print(arr.transpose((1,0,2)))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [8]:
print(arr.transpose((0,2,1)))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [9]:
# 与上式等价的swapaxes方法
print(arr.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]
