In [1]:
import numpy as np
import pandas as pd

### numpy中的array的广播机制
+ 默认在行上进行广播

In [4]:
arr = np.arange(12.).reshape((3,4))
print(f"arr = \n{arr}")

arr = 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [3]:
print(f"arr[0] = \n{arr[0]}")

arr[0] = 
[0. 1. 2. 3.]


In [5]:
print(f"arr - arr[0] = \n{arr - arr[0]}")

arr - arr[0] = 
[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]


### DataFrame的广播机制

In [8]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
series = frame.iloc[0]
print(frame)
print('--------------------------------')
print(series)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
--------------------------------
b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64


In [9]:
print(frame - series)

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0


如果一个索引值不在DataFrame的列中，也不在Series的索引中，则对象会重建索引并形成联合

In [11]:
series2 = pd.Series(range(3),index=['b','e','f'])
print(series2)
print('--------------------------------')
print(frame+series2)

b    0
e    1
f    2
dtype: int64
--------------------------------
          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN


#### 在列上广播
要显式指定axis

In [12]:
series3 = frame['d']
print(series3)
print('--------------------------------')
print(frame.sub(series3,axis='index'))

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64
--------------------------------
          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0
